spring:
  application:
    name: ics
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: postgres
    password: postgres
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3.2:1b # or any other model you want to use
      embedding:
        enabled: true
        model: nomic-embed-text # or any other embedding model you want to use
  vectorstore:
    pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      dimensions: 768
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2MB
server:
  tomcat:
    max-http-form-post-size: 100MB
    max-swallow-size: 100MB
    max-http-header-size: 16KB
